### ISSUE TITLE
Bad Path Param

### ISSUE THREAD

**Issue by starman85** [dharmatech/net-liquidity.ps1#4]
Hey there,

Seems something has changed and we can't pull the TGA numbers

Invoke-RestMethod: /Users/1234/Code/net-liquidity.ps1/net-liquidity-walcl.ps1:8:15
Line |
   8 |  …   $result = Invoke-RestMethod -Method Get -Uri ('https://api.fiscalda …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"error":"Bad Path Param","message":"Path parameter fiscal_service/v1/accounting/dts/dts_table_1 does not exist, for more information please see the documentation."}
InvalidOperation: /Users/1234/Code/net-liquidity.ps1/net-liquidity-walcl.ps1:59:1
Line |
  59 |  $earliest = ($tga_dates | Sort-Object)[0]
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.

**Comment by dharmatech** [comment]
Use this script instead:

net-liquidity-earnings-remittances.ps1

https://github.com/dharmatech/net-liquidity.ps1/blob/master/net-liquidity-earnings-remittances.ps1

**Comment by starman85** [comment]
Thanks that worked :)

Regarding your Cron scripts, im presuming you're running them according to the schedule mentioned in the readme? Do you do the same for your various other scripts?
